name: gee_player
description: "Gee Player: local video and music playback with subtitles."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  drift: 2.35.0
  drift_flutter: 0.3.1
  file_selector: 1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: 3.4.3
  media_kit: 1.2.6
  media_kit_libs_video: 1.0.7
  media_kit_video: 2.0.1
  path_provider: 2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: 2.35.0
  build_runner: 2.15.1

flutter:
  uses-material-design: true
